# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GipRouter
                                 A QGIS plugin
 Router for austrian official open government street graph
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-03-03
        copyright            : (C) 2019 by Dominic Winkler
        email                : office@flexarts.at
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GipRouter class from file GipRouter.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .gip_router import GipRouter
    return GipRouter(iface)
